version: '3.7'
services:
    go-api:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./src:/usr/src/app/src
        ports:
            - "8002:8000"
        container_name: go-api
        command: ./out/go-api